# Generated by Django 4.0.4 on 2022-04-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
