# Generated by Django 4.0.4 on 2022-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='default.png', upload_to='photos/'),
        ),
    ]
