# Generated by Django 4.0.4 on 2022-04-19 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0009_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='joins',
            field=models.ManyToManyField(blank=True, related_name='joins', to=settings.AUTH_USER_MODEL),
        ),
    ]
